{% set name = "dm-haiku" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0c1d56ef20e1e04d8551f788ff8964167092c5d8051b7c17ed3f9ce60c0b0a59

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - absl-py >=0.7.1
    - jmp >=0.0.2
    - numpy >=1.18.0
    - tabulate >=0.8.9
    - flax >=0.7.1

test:
  imports:
    - haiku
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/deepmind/dm-haiku
  license: Apache-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Haiku is a library for building neural networks in JAX.
  description: |
    Haiku is a simple neural network library for JAX developed by some 
    of the authors of Sonnet, a neural network library for TensorFlow.
  doc_url: https://github.com/deepmind/dm-haiku
  dev_url: https://dm-haiku.readthedocs.io/

extra:
  recipe-maintainers:
    - jan-janssen
