{% set name = "dm-haiku" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dm-haiku-{{ version }}.tar.gz
  sha256: ba0b3acf71433156737fe342c486da11727e5e6c9e054245f4f9b8f0b53eb608

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - absl-py >=0.7.1
    - jmp >=0.0.2
    - numpy >=1.18.0
    - tabulate >=0.8.9
    - flax >=0.7.1

test:
  imports:
    - haiku
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/dm-haiku
  license: Apache-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Haiku is a library for building neural networks in JAX.
  description: |
    Haiku is a simple neural network library for JAX developed by some 
    of the authors of Sonnet, a neural network library for TensorFlow.
  doc_url: https://github.com/deepmind/dm-haiku
  dev_url: https://dm-haiku.readthedocs.io/

extra:
  recipe-maintainers:
    - jan-janssen
